//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporsalonuBYSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercis
    {
        public int ExercisesID { get; set; }
        public int TrainerID { get; set; }
        public string ExerciseName { get; set; }
        public string Description { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
